[package]
name = "pihole"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0"
reqwest = { version = "0", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
mockito = "1"
